"""add document_chunks and document_tables

Revision ID: 96d4f7cffbed
Revises: 
Create Date: 2025-11-01 08:35:08.897778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96d4f7cffbed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('document_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('table_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_tables_id'), 'document_tables', ['id'], unique=False)
    op.drop_index('ix_capital_calls_id', table_name='capital_calls')
    op.drop_table('capital_calls')
    op.drop_index('ix_adjustments_id', table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_index('ix_distributions_id', table_name='distributions')
    op.drop_table('distributions')
    op.drop_index('document_embeddings_embedding_idx', table_name='document_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('document_embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='document_embeddings_pkey')
    )
    op.create_index('document_embeddings_embedding_idx', 'document_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('distributions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distribution_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('distribution_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_recallable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name='distributions_fund_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='distributions_pkey')
    )
    op.create_index('ix_distributions_id', 'distributions', ['id'], unique=False)
    op.create_table('adjustments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('adjustment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('adjustment_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_contribution_adjustment', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name='adjustments_fund_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='adjustments_pkey')
    )
    op.create_index('ix_adjustments_id', 'adjustments', ['id'], unique=False)
    op.create_table('capital_calls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('call_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('call_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name='capital_calls_fund_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='capital_calls_pkey')
    )
    op.create_index('ix_capital_calls_id', 'capital_calls', ['id'], unique=False)
    op.drop_index(op.f('ix_document_tables_id'), table_name='document_tables')
    op.drop_table('document_tables')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
