"""add embedding column to document_chunks

Revision ID: f84934a9120a
Revises: 96d4f7cffbed
Create Date: 2025-11-01 16:31:51.171284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f84934a9120a'
down_revision: Union[str, None] = '96d4f7cffbed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_capital_calls_id', table_name='capital_calls')
    op.drop_table('capital_calls')
    op.drop_index('ix_adjustments_id', table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_index('ix_distributions_id', table_name='distributions')
    op.drop_table('distributions')
    op.add_column('document_chunks', sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    op.create_table('distributions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distribution_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('distribution_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_recallable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name='distributions_fund_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='distributions_pkey')
    )
    op.create_index('ix_distributions_id', 'distributions', ['id'], unique=False)
    op.create_table('adjustments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('adjustment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('adjustment_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_contribution_adjustment', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name='adjustments_fund_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='adjustments_pkey')
    )
    op.create_index('ix_adjustments_id', 'adjustments', ['id'], unique=False)
    op.create_table('capital_calls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('call_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('call_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name='capital_calls_fund_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='capital_calls_pkey')
    )
    op.create_index('ix_capital_calls_id', 'capital_calls', ['id'], unique=False)
    # ### end Alembic commands ###
